#!/usr/bin/env bash
# install.sh — orchestrate stow-based dotfiles installation.
#
# Idempotent: safe to re-run. Backs up any pre-existing real files in $HOME
# that would conflict with stow links into a timestamped backup dir.
#
# Host configuration:
#   hosts/<hostname>.conf declares BREW_MODULES=(...).
#   Unknown hosts install the baseline only.
#
# Usage:
#   ./install.sh              # interactive (prompts for brew)
#   ./install.sh --brew       # force brew bundle
#   ./install.sh --no-brew    # skip brew bundle
#   ./install.sh --no-prompt  # skip all prompts (use defaults)
#   HOST_OVERRIDE=foo ./install.sh   # pretend hostname is 'foo'

set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DOTFILES_DIR"

# All stow packages present in the repo.
PACKAGES_ALL=(
  brew zsh git gh nvim ghostty tmux hammerspoon
  linearmouse skhd yabai zed ssh claude
)

# macOS-only stow packages (skipped on Linux).
MACOS_ONLY_PACKAGES=(hammerspoon linearmouse skhd yabai)

WANT_BREW=""   # empty=prompt, 1=yes, 0=no
NO_PROMPT=0
for arg in "$@"; do
  case "$arg" in
    --brew)      WANT_BREW=1 ;;
    --no-brew)   WANT_BREW=0 ;;
    --no-prompt) NO_PROMPT=1 ;;
    -h|--help)   sed -n '2,18p' "$0"; exit 0 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

c_red='\033[31m'; c_yel='\033[33m'; c_grn='\033[32m'; c_dim='\033[2m'; c_off='\033[0m'
say()  { printf '%b\n' "$*"; }
info() { say "${c_dim}  $*${c_off}"; }
warn() { say "${c_yel}! $*${c_off}"; }
ok()   { say "${c_grn}✓ $*${c_off}"; }
err()  { say "${c_red}✗ $*${c_off} " >&2; }

confirm() {
  (( NO_PROMPT )) && return 0
  local prompt="$1" reply
  # Read from the terminal directly so prompts work even when the caller
  # loop has stdin bound to a process substitution (e.g. while < <(find)).
  read -r -p "$prompt [y/N] " reply </dev/tty
  [[ "$reply" =~ ^[Yy]$ ]]
}

# Like confirm, but --no-prompt declines. Use for destructive prompts where
# the safe default is "no".
confirm_safe() {
  (( NO_PROMPT )) && return 1
  local prompt="$1" reply
  read -r -p "$prompt [y/N] " reply </dev/tty
  [[ "$reply" =~ ^[Yy]$ ]]
}

case "$(uname -s)" in
  Darwin) IS_MACOS=1 ;;
  *)      IS_MACOS=0 ;;
esac

HOST="${HOST_OVERRIDE:-$(hostname -s)}"
HOST_CONF="$DOTFILES_DIR/hosts/${HOST}.conf"

BREW_MODULES=()

if [[ -f "$HOST_CONF" ]]; then
  # shellcheck disable=SC1090
  source "$HOST_CONF"
  info "host '$HOST': loaded $HOST_CONF"
else
  warn "unknown host '$HOST' — baseline only."
  info "create $HOST_CONF to enable optional modules (see hosts/default.conf)."
fi

if (( IS_MACOS )); then
  info "os: macOS"
else
  info "os: $(uname -s) (non-macOS: skipping brew + macOS-only packages)"
fi

command -v stow >/dev/null || { err "GNU stow not installed (brew install stow / apt install stow)"; exit 1; }

BREW_HOME="$DOTFILES_DIR/brew/.config/homebrew"

run_brew_bundle() {
  command -v brew >/dev/null || { warn "brew not found, skipping bundle"; return 0; }

  local generated="$BREW_HOME/Brewfile.generated"
  local base="$BREW_HOME/Brewfile.base"

  [[ -f "$base" ]] || { err "missing $base"; return 1; }

  {
    echo "# Generated by install.sh for host '$HOST' at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Modules: base ${BREW_MODULES[*]:-}"
    echo
    cat "$base"
    for mod in "${BREW_MODULES[@]:-}"; do
      [[ -z "$mod" ]] && continue
      local modfile="$BREW_HOME/Brewfile.${mod}"
      if [[ ! -f "$modfile" ]]; then
        warn "module '$mod' declared but $modfile missing — skipping"
        continue
      fi
      echo
      echo "# --- module: $mod ---"
      cat "$modfile"
    done
  } > "$generated"

  say "${c_dim}── brew bundle (Brewfile.generated) ──${c_off}"
  brew bundle --file="$generated"
}

if (( IS_MACOS )); then
  if [[ -z "$WANT_BREW" ]]; then
    if (( NO_PROMPT )) || confirm "Run brew bundle for host '$HOST'?"; then
      WANT_BREW=1
    else
      WANT_BREW=0
    fi
  fi
  if (( WANT_BREW )); then
    run_brew_bundle
  else
    info "skipping brew bundle"
  fi
else
  info "skipping brew bundle (non-macOS)"
fi

mkdir -p "$HOME/.config/zsh" "$HOME/.cache/zsh"

is_macos_only() {
  local p="$1"
  for m in "${MACOS_ONLY_PACKAGES[@]}"; do
    [[ "$p" == "$m" ]] && return 0
  done
  return 1
}

PACKAGES=()
for p in "${PACKAGES_ALL[@]}"; do
  if (( ! IS_MACOS )) && is_macos_only "$p"; then
    info "skip macOS-only package: $p"
    continue
  fi
  PACKAGES+=("$p")
done

BACKUP_DIR="$HOME/.dotfiles-backup/$(date +%Y%m%d-%H%M%S)"

move_to_backup() {
  local target="$1" rel="$2"
  mkdir -p "$BACKUP_DIR/$(dirname "$rel")"
  mv "$target" "$BACKUP_DIR/$rel"
  info "backed up $target → $BACKUP_DIR/$rel"
}

backup_conflicts() {
  local pkg="$1"
  while IFS= read -r -d '' src; do
    local rel="${src#$DOTFILES_DIR/$pkg/}"
    local target="$HOME/$rel"

    [[ -e "$target" && ! -L "$target" ]] || continue

    if cmp -s "$src" "$target"; then
      move_to_backup "$target" "$rel"
      continue
    fi

    warn "conflict: $target differs from repo"
    if ! confirm_safe "  overwrite repo copy with home version?"; then
      info "  kept repo version; home copy moved to backup"
      move_to_backup "$target" "$rel"
      continue
    fi

    cp -p "$target" "$src"
    move_to_backup "$target" "$rel"
    info "adopted $target → ${src#$DOTFILES_DIR/}"
  done < <(find "$DOTFILES_DIR/$pkg" -type f -not -path '*/.git/*' -print0)
}

say "${c_dim}── stow ──${c_off}"
for pkg in "${PACKAGES[@]}"; do
  if [[ ! -d "$DOTFILES_DIR/$pkg" ]]; then
    warn "skip missing package: $pkg"; continue
  fi
  backup_conflicts "$pkg"
  if stow -v --no-folding -t "$HOME" "$pkg" 2>&1 | sed "s/^/  /"; then
    ok "stowed $pkg"
  else
    err "failed to stow $pkg"
  fi
done

[[ -d "$BACKUP_DIR" ]] && warn "originals preserved in $BACKUP_DIR"

if (( IS_MACOS )); then
  if [[ ! -e "$HOME/.hammerspoon" ]]; then
    ln -s "$HOME/.config/hammerspoon" "$HOME/.hammerspoon"
    ok "linked ~/.hammerspoon → ~/.config/hammerspoon"
  fi
fi

LOCAL_ZSH="$HOME/.config/zsh/99-local.zsh"
if [[ ! -e "$LOCAL_ZSH" ]]; then
  cat > "$LOCAL_ZSH" <<'EOF'
# 99-local.zsh — host-specific overrides. NOT tracked in dotfiles repo.
# Put any per-machine env, secrets-not-in-Bitwarden, or experimental code here.
EOF
  chmod 600 "$LOCAL_ZSH"
  ok "created $LOCAL_ZSH"
fi

if command -v lefthook >/dev/null; then
  (cd "$DOTFILES_DIR" && lefthook install >/dev/null 2>&1) \
    && ok "lefthook hooks installed" \
    || warn "lefthook install failed"
else
  warn "lefthook not installed (run brew bundle to get it)"
fi

mkdir -p "$HOME/.cache/zsh"
touch "$HOME/.cache/zsh/dotfiles-last-sync"
printf 'no\n' > "$HOME/.cache/zsh/dotfiles-drift-check"

REMINDER_FLAG="$HOME/.cache/zsh/dotfiles-sync-reminder"
if [[ ! -f "$REMINDER_FLAG" ]]; then
  if confirm "Enable monthly shell-start reminder to run 'dotsync'?"; then
    touch "$REMINDER_FLAG"
    ok "reminder enabled (rm $REMINDER_FLAG to disable)"
  fi
fi

cat <<EOF

${c_grn}✓ install complete${c_off} (host: $HOST, modules: base ${BREW_MODULES[*]:-})

Next steps:
  ${c_dim}# Restart your shell:${c_off}
  exec zsh

  ${c_dim}# Initialize Bitwarden CLI for secrets (run once):${c_off}
  rbw config set email YOUR_EMAIL
  rbw config set pinentry pinentry-mac
  rbw login

  ${c_dim}# Restore Claude plugins from installed_plugins.json:${c_off}
  bash $DOTFILES_DIR/scripts/install-claude-plugins.sh

  ${c_dim}# Apply macOS system defaults (optional):${c_off}
  bash $DOTFILES_DIR/scripts/macos-defaults.sh
EOF

if (( IS_MACOS )); then
  cat <<EOF

  ${c_dim}# yabai sudoers entry is auto-refreshed by the brew zsh wrapper after${c_off}
  ${c_dim}# every install/upgrade. SIP must be partially disabled for --load-sa${c_off}
  ${c_dim}# to take effect — the wrapper warns if it isn't.${c_off}
EOF
fi
