// Auto-generated by moshi-hook. Update with care.
import { createConnection } from "node:net"
import { homedir } from "node:os"
import { join as pathJoin } from "node:path"
import type { Plugin } from "@opencode-ai/plugin"

// Kept for debug / manual invocation. Routine events go straight to the
// daemon's Unix socket (see resolveSocketPath) — no subprocess spawn.
const helperBinary = "/opt/homebrew/bin/moshi-hook"

// Mirrors internal/config.SocketPath. The MOSHI_SOCKET_PATH override wins
// over the per-platform default so tests and dev daemons can point us at a
// throwaway socket.
function resolveSocketPath(): string {
  const override = process.env.MOSHI_SOCKET_PATH
  if (override) return override
  if (process.platform === "darwin") {
    return pathJoin(homedir(), "Library", "Application Support", "Moshi", "moshi-hook.sock")
  }
  if (process.env.XDG_RUNTIME_DIR) {
    return pathJoin(process.env.XDG_RUNTIME_DIR, "moshi-hook.sock")
  }
  return "/tmp/moshi-hook.sock"
}

interface DaemonResponse {
  type?: string
  decision?: string
  error?: string
}

// One-message-per-connection wire protocol (see internal/socket/server.go):
// dial, write one envelope as a JSON line, optionally read one response,
// close. Errors and timeouts resolve to null so callers degrade gracefully:
// fire-and-forget drops silently, permission.ask falls through to OpenCode's
// default handling.
function sendEnvelope(
  envelope: Record<string, unknown>,
  opts: { wait: boolean; waitTimeoutMs?: number },
): Promise<DaemonResponse | null> {
  return new Promise((resolve) => {
    let settled = false
    const finish = (val: DaemonResponse | null) => {
      if (settled) return
      settled = true
      try {
        sock.destroy()
      } catch {}
      resolve(val)
    }

    const sock = createConnection({ path: resolveSocketPath() })
    sock.setNoDelay(true)
    sock.once("error", () => finish(null))

    if (opts.wait && opts.waitTimeoutMs) {
      setTimeout(() => finish(null), opts.waitTimeoutMs).unref?.()
    }

    sock.once("connect", () => {
      sock.write(JSON.stringify(envelope) + "\n")
      if (!opts.wait) {
        // Fire-and-forget from the caller's perspective, but still half-close
        // and read the daemon ack so the daemon does not log broken pipes.
        sock.end()
      }
    })

    const chunks: Buffer[] = []
    sock.on("data", (b: Buffer) => chunks.push(b))
    const parse = () => {
      if (settled) return
      const text = Buffer.concat(chunks).toString("utf8").trim()
      if (!text) return finish(null)
      try {
        finish(JSON.parse(text.split("\n")[0]) as DaemonResponse)
      } catch {
        finish(null)
      }
    }
    sock.once("end", parse)
    sock.once("close", parse)
  })
}

function projectNameFromCwd(cwd: string | undefined): string {
  if (!cwd) return ""
  const trimmed = cwd.replace(/\/+$/, "")
  const idx = trimmed.lastIndexOf("/")
  return idx >= 0 ? trimmed.slice(idx + 1) : trimmed
}

function prettyToolName(toolName: string) {
  switch (toolName) {
    case "bash":
      return "Bash"
    case "edit":
      return "Edit"
    case "write":
      return "Write"
    case "webfetch":
      return "WebFetch"
    case "websearch":
    case "codesearch":
      return "WebSearch"
    case "task":
      return "Task"
    default:
      return toolName
  }
}

// Mirrors internal/cli/hook.go newSessionID — 16 hex chars, used when
// OpenCode hands us an event with no sessionID (rare but possible on
// initialisation paths).
function newSessionID(): string {
  const buf = new Uint8Array(8)
  crypto.getRandomValues(buf)
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("")
}

function subtitleForPermission(name: string): string {
  switch (name) {
    case "bash":
      return "Waiting for command approval"
    case "edit":
      return "Waiting for file edit approval"
    case "external_directory":
      return "Waiting for directory access approval"
    default:
      return "Waiting for approval"
  }
}

function stringProp(obj: Record<string, unknown>, ...keys: string[]): string {
  for (const key of keys) {
    const val = obj[key]
    if (typeof val === "string" && val.length > 0) return val
  }
  return ""
}

function patternsFromPermission(permission: Record<string, unknown>): string[] {
  const rawPatterns = permission.patterns ?? permission.pattern
  const patterns: string[] = Array.isArray(rawPatterns)
    ? rawPatterns.filter((p): p is string => typeof p === "string" && p.length > 0)
    : typeof rawPatterns === "string" && rawPatterns.length > 0
      ? [rawPatterns]
      : []
  return patterns
}

function permissionName(permission: Record<string, unknown>): string {
  return stringProp(permission, "permission", "type") || "permission"
}

function summarizePermission(permission: Record<string, unknown>): string {
  const patterns = patternsFromPermission(permission)
  const title = stringProp(permission, "title")
  if (title) return title
  const name = permissionName(permission)
  if (patterns.length === 0) {
    return name ? name + " permission requested" : "Permission requested"
  }
  return name + ": " + patterns[0]
}

function sendSessionUpdate(
  eventName: string,
  sessionID: string | undefined,
  directory: string,
  toolName?: string,
  category?: string,
  title?: string,
  message?: string,
): void {
  void sendEnvelope(
    {
      type: "session.update",
      source: "opencode",
      sessionId: sessionID || newSessionID(),
      eventName,
      cwd: directory,
      projectName: projectNameFromCwd(directory),
      toolName: toolName ?? "",
      category: category ?? "",
      title: title ?? "OpenCode session",
      message: message ?? "",
      requestedAt: new Date().toISOString(),
    },
    { wait: false },
  )
}

function eventRecord(event: { properties?: unknown }): Record<string, unknown> {
  return event.properties && typeof event.properties === "object"
    ? event.properties as Record<string, unknown>
    : {}
}

function sessionIDFromProperties(props: Record<string, unknown>): string | undefined {
  const direct = stringProp(props, "sessionID", "sessionId", "id")
  if (direct) return direct
  const info = props.info
  if (info && typeof info === "object") return stringProp(info as Record<string, unknown>, "id", "sessionID", "sessionId")
  return undefined
}

function directoryFromProperties(props: Record<string, unknown>, fallback: string): string {
  const direct = stringProp(props, "directory", "cwd")
  if (direct) return direct
  const info = props.info
  if (info && typeof info === "object") {
    const fromInfo = stringProp(info as Record<string, unknown>, "directory", "cwd")
    if (fromInfo) return fromInfo
  }
  return fallback
}

function permissionFromEventProperties(props: Record<string, unknown>): Record<string, unknown> {
  const nested = props.permission
  if (nested && typeof nested === "object") return nested as Record<string, unknown>
  return props
}

function statusTypeFromProperties(props: Record<string, unknown>): string {
  const status = props.status
  if (status && typeof status === "object") return stringProp(status as Record<string, unknown>, "type")
  return stringProp(props, "status")
}

function openCodeReplyForDecision(decision: string | undefined): "once" | "reject" | null {
  switch (decision) {
    case "approve":
      return "once"
    case "deny":
      return "reject"
    default:
      return null
  }
}

const approvalRequests = new Map<string, Promise<DaemonResponse | null>>()

function requestMoshiApproval(
  permission: Record<string, unknown>,
  directory: string,
  eventName: string,
): Promise<DaemonResponse | null> | null {
  const actionID = stringProp(permission, "id", "permissionID", "permissionId", "requestID", "requestId")
  if (!actionID) return null

  const existing = approvalRequests.get(actionID)
  if (existing) return existing

  const name = permissionName(permission)
  const expiresAt = new Date(Date.now() + 5 * 60_000).toISOString()
  const promise = sendEnvelope(
    {
      type: "approval.request",
      source: "opencode",
      sessionId: stringProp(permission, "sessionID", "sessionId") || newSessionID(),
      actionId: actionID,
      eventName,
      phase: "waitingForApproval",
      category: "approval_required",
      cwd: directory,
      projectName: projectNameFromCwd(directory),
      toolName: name,
      title: "OpenCode permission",
      subtitle: subtitleForPermission(name),
      message: summarizePermission(permission),
      expiresAt,
      requestedAt: new Date().toISOString(),
    },
    { wait: true, waitTimeoutMs: 5 * 60_000 + 5_000 },
  ).finally(() => {
    approvalRequests.delete(actionID)
  })
  approvalRequests.set(actionID, promise)
  return promise
}

async function replyToOpenCodePermission(
  client: Record<string, unknown>,
  permission: Record<string, unknown>,
  reply: "once" | "reject",
  directory: string,
): Promise<void> {
  const actionID = stringProp(permission, "id", "permissionID", "permissionId", "requestID", "requestId")
  const sessionID = stringProp(permission, "sessionID", "sessionId")
  const fn = client.postSessionIdPermissionsPermissionId
  if (!actionID || !sessionID || typeof fn !== "function") return
  try {
    await fn.call(client, {
      path: { id: sessionID, permissionID: actionID },
      query: { directory },
      body: { response: reply },
    })
  } catch {}
}

const server: Plugin = async ({ directory, client }) => ({
  event: async ({ event }) => {
    const props = eventRecord(event)
    switch (event.type) {
      case "session.created": {
        const cwd = directoryFromProperties(props, directory)
        sendSessionUpdate("session.created", sessionIDFromProperties(props), cwd, undefined, "session_started", "OpenCode session")
        break
      }
      case "session.status": {
        const statusType = statusTypeFromProperties(props)
        const cwd = directoryFromProperties(props, directory)
        if (statusType === "busy") {
          sendSessionUpdate("session.status", sessionIDFromProperties(props), cwd, undefined, "session_started", "OpenCode session")
        } else if (statusType === "idle") {
          sendSessionUpdate("session.status", sessionIDFromProperties(props), cwd, undefined, "task_complete", "OpenCode session idle")
        } else {
          sendSessionUpdate("session.status", sessionIDFromProperties(props), cwd, undefined, "", "OpenCode session", statusType)
        }
        break
      }
      case "session.idle":
        sendSessionUpdate("session.idle", sessionIDFromProperties(props), directory, undefined, "task_complete", "OpenCode session idle")
        break
      case "permission.asked":
      case "permission.updated": {
        const permission = permissionFromEventProperties(props)
        const promise = requestMoshiApproval(permission, directory, event.type)
        if (!promise) break
        const result = await promise
        const reply = openCodeReplyForDecision(result?.decision)
        if (reply) await replyToOpenCodePermission(client as unknown as Record<string, unknown>, permission, reply, directory)
        break
      }
      case "permission.replied":
        sendSessionUpdate("permission.replied", sessionIDFromProperties(props), directory)
        break
      default:
        break
    }
  },
  "tool.execute.before": async (input) => {
    sendSessionUpdate("tool.execute.before", input.sessionID, directory, prettyToolName(input.tool), "tool_running", prettyToolName(input.tool))
  },
  "tool.execute.after": async (input) => {
    sendSessionUpdate("tool.execute.after", input.sessionID, directory, prettyToolName(input.tool), "tool_finished", prettyToolName(input.tool))
  },
  "permission.ask": async (input, output) => {
    const result = await requestMoshiApproval(input as Record<string, unknown>, directory, "permission.ask")

    switch (result?.decision) {
      case "approve":
        output.status = "allow"
        break
      case "deny":
        output.status = "deny"
        break
      default:
        break
    }
  },
})

export default {
  id: "moshi-hooks",
  server,
}
