onboarding = false

[experimental]
pane_history = false

[keys]
prefix = "ctrl+h"
focus_pane_left = "prefix+t"
split_horizontal = "prefix+h"
split_vertical = "prefix+v"
next_tab = "prefix+n"
previous_tab = "prefix+p"
switch_tab = "cmd+1..9"
previous_workspace = "cmd+["
next_workspace = "cmd+]"
goto = "prefix+g"
new_tab = "prefix+c"

[ui.toast]
delivery = "system"

[terminal]
default_shell = "zsh"
new_cwd = "follow"

[theme]
name = "tokyo-night"

[ui]
agent_panel_scope = "all"
